AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  go-sam-pipes

  Demo SAM Pipelines

Resources:
  HelloService:
    Type: AWS::Serverless::Application
    Properties:
      Location: hello-template.yaml
  
  GoodbyeService:
    Type: AWS::Serverless::Application
    Properties:
      Location: goodbye-template.yaml
  